name: "Set Issue Label on Tech"
on:
  issues:
    types: [opened]
  pull_request:
    typed: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "title"
          parameters: '[ {"keywords": ["Solar", "solar"], "labels": ["Technology: Solar"]}, {"keywords": ["Hydrogen", "hydrogen"], "labels": ["Technology: Hydrogen"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
