name: "Set Issue Label on Country"
on:
  issues:
    types: [opened]
  pull_request:
    typed: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "title"
          parameters: '[ {"keywords": ["Spain", "spain"], "labels": ["Country: Spain"], "assignees": ["pcvicente-thema"]}, {"keywords": ["Spain", "spain"], "labels": ["Country: Spain"], "assignees": ["pcvicente-thema"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
